# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4dfff622e9414ad1abf7ab1bf5f3a8be21c53d8cfb9166d36aaf8854ca76d695fd6bcf5babda696f3406781c882abb0f3c1a65f0d6a00d6c815f2ed26c6577b2

test:
  secret_key_base: bc4fd931e9631566f8429467dddd587e8aa4d3370c35ba95a12f4c99f8b0f1feaca1fbe9c534f0638117c204dc9bd18291ee49dd2da368a82f274347f57226bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
